### ISSUE TITLE
Unchanged campaign map

### ISSUE THREAD

**Issue by K-RL** [sargeantPig/RTWRandomiser#3]
**Describe the bug**
After randomising and launching the game, the menu shows the randomised world map but once I start playing, the faction occupies the vanilla regions.

**To Reproduce**
1. Installed the mod as described in the Installation Section.
2. Launched the program with administrator privileges.
3. ![image](https://user-images.githubusercontent.com/55942930/118398928-f9d91f00-b65a-11eb-8953-e8d11ef8de71.png)
4. Seed is 287456855
5. Launched the game with the play button
6. clicked on "ok" when steam prompted me with the message thingy
7. checked the randomised mod in the launcher's mod manager (only mod enabled)
8. Selected the Greek Cities
9. ![image](https://user-images.githubusercontent.com/55942930/118398988-4ae91300-b65b-11eb-911a-7bbcfc6f0275.png)

**Expected behavior**
I expected to have only one city in southern gaul but started in Greece with Syracuse and the other vanilla greek cities.
![image](https://user-images.githubusercontent.com/55942930/118399013-65bb8780-b65b-11eb-8586-7c5ff3ecee79.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: Total War Rome Remastered v2.0

**Comment by K-RL** [comment]
Well it seems that selecting classic campaign options was the problem.
If everything is set to remaster it works correctly. Would love to play with classic population balancing and no merchants though.

**Comment by sargeantPig** [comment]
Thanks for pointing this issue out and in great detail!

I didn't think those options would impact the descr_strat but apparently so. Will likely fix this for the next update.

(reopening until fixed)

**Comment by sargeantPig** [comment]
Fixed as of bfec2d3bc428202ba3abac49a7e7aea1ccb8eb1d
